[package]
authors = ["cyqsimon"]
description = "Making Rust a true modern language™️ with revolutionary macros."
documentation = "https://docs.rs/zoomer"
edition = "2021"
license = "MIT"
name = "zoomer"
repository = "https://github.com/cyqsimon/zoomer-rs"
version = "0.1.2"

[dependencies]
